name: Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Prepare java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '8'

      - name: Prepare dotnet
        uses: xt0rted/setup-dotnet@v1.5.0

      - name: Prepare Clojure CLR
        run: |
          dotnet tool install --global Clojure.Main --version 1.12.0-alpha10
          dotnet tool install --global Clojure.Cljr --version 0.1.0-alpha4

      - name: Install clojure tools
        uses: DeLaGuardo/setup-clojure@10.1
        with:
          lein: 2.9.10

      - name: Cache clojure dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: cljdeps-${{ hashFiles('project.clj') }}
          restore-keys: cljdeps-

      - name: Run clj and cljs tests
        run: lein test-all

      - name: Run cljr tests
        run: cljr -X:test
